version: 0.2
phases:
  install:      
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - echo Restore started on `date`
      - ls
      - pwd
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet tool install -g Microsoft.Web.LibraryManager.Cli
      - dotnet tool install --global Amazon.Lambda.Tools --version 3.3.1
      - aws s3 cp ~/wwwroot/ s3://content-slaytonhub.s3.amazonaws.com/wwwroot/
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output SlaytonHub/src/SlaytonHub/SlaytonHub.csproj
  post_build:
    commands:
      - 
      