name: Deploy AWS Resources

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    
    - name: Install Amazon.Lambda.Tools
      run: |
          dotnet tool install --global Amazon.Lambda.Tools
          echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
    - name: see whats up          
      run: pwd
    - name: see whats up          
      run: ls
    - name: Release 
      run: dotnet lambda deploy-serverless -sn SlaytonHub --s3-bucket slaytonhub -sp /SlaytonHub/ -cfg SlaytonHub/src/SlaytonHub/aws-lambda-tools-defaults.json
